#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if command -v pyenv &> /dev/null && [ -f .python-version ]; then
    pyenv install -s "$(cat .python-version)"
fi

pip install poetry
poetry config virtualenvs.in-project true
poetry install